### ISSUE TITLE
[BUG]: Even with @async, larger PSRN networks significantly slow down the main search loop

### ISSUE THREAD

**Issue by x66ccff** [x66ccff/PTS.jl#4]
### What happened?

Hi @MilesCranmer, I've successfully integrated PSRN with PySR, but I'm facing an issue: when I increase the number of input subtrees for PSRN, it significantly slows down the execution of the main loop. Currently, I'm using `@async `to start the PSRN search, and I've also tried using Cursor to change it to `@spawn,` but the problem persists. Since I'm not very familiar with Julia, I hope to get some help!

https://github.com/x66ccff/PTS.jl/blob/60085083d0cfcc439130b0feeb13d0cd91f675ce/src/SymbolicRegression.jl#L1024-L1037

You can now run searches with the PSRN module using:

```bash
julia --project=. dev/debug.jl
```

You might need to install these packages first in the Julia package manager:
```julia
add CUDA
add KernelAbstractions
```

### Version

None

### Operating System

Linux

### Interface

Julia REPL

**Comment by MilesCranmer** [comment]
Hm, maybe check https://docs.julialang.org/en/v1/manual/performance-tips/?

**Comment by x66ccff** [comment]
> Hm, maybe check https://docs.julialang.org/en/v1/manual/performance-tips/?

Thanks, I'll take a look.

**Comment by x66ccff** [comment]
Okay, finally figured out that using export JULIA_NUM_THREADS=4 works 😂, since by default Julia uses only one thread.
